Fix: Remove hex_to_bytes declaration from header
Since hex_to_bytes is now static (internal use only), it should not
be declared in the header file. This fixes the compilation error:
'static declaration follows non-static declaration'