usrloc: Fix compiler warning
dlist.c: In function ‘get_all_ucontacts’:
dlist.c:750:37: error: ‘next_hop_host’ may be used uninitialized in this
			    function [-Werror=maybe-uninitialized]
      ((struct proxy_l *)cp)->name.s = next_hop_host;
                                     ^

(cherry picked from commit 95edbd2c8cd8ed208248b8f47805654a41e5e129)