Work around a few poor compiler warnings
Like:

    dlist.c: In function ‘get_all_ucontacts’:
    dlist.c:759:37: error: ‘next_hop_host’ may be used uninitialized in this
      function [-Werror=maybe-uninitialized]

And:

    In function ‘memcpy’,
      inlined from ‘get_domain_db_ucontacts’ at dlist.c:294:4:
    /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34:10: error:
      ‘__builtin_memcpy’: specified size between 18446744071562067968 and
      18446744073709551615 exceeds maximum object size 9223372036854775807
      [-Werror=stringop-overflow=]

And one probable bug:

    b2b_logic.c: In function ‘mi_b2b_list’:
    b2b_logic.c:1548:10: error: ‘server_item’ may be used uninitialized in this
        function [-Werror=maybe-uninitialized]
    ^- should be client_item

(cherry picked from commit 94c50b7811e1af69ef1400c531b0b6196e3ffb39)