Fix compiler warnings with -DUSE_FUTEX
Specifically:
    futex_lock.h:78: warning: implicit declaration of function ‘syscall’

This warning appears since glibc version 2.19, along with the
introduction of the _DEFAULT_SOURCE FTM, which is a macro that seems to
be additionally required when defining any of the previous FTMs...

man feature_test_macros