Fix build on ARM architectures
Compiling mod_fix.c
In file included from mem/../lock_alloc.h:55:0,
                 from mem/../locking.h:66,
                 from mem/../statistics.h:155,
                 from mem/hp_malloc.h:29,
                 from mem/common.h:46,
                 from mem/mem.h:37,
                 from mod_fix.c:25:
mem/../mem/shm_mem.h: In function ‘shm_threshold_check’:
mem/../mem/shm_mem.h:250:5: error: ‘shm_block’ undeclared

Fixes #1725

(cherry picked from commit 8d43873f42e6901e83a0cb5c1cae42bce7d0a886)