msrp_ua: Fix gcc false positives on ubuntu-18.04
msrp_ua.c:2443:3: error: ‘hdl.param’ may be used uninitialized in
this function [-Werror=maybe-uninitialized]
   hdl.notify_cb(&cb_params, hdl.param);

(cherry picked from commit a7f737c6835825c529e5c83f493ae119303c7b61)