proto_msrp: Fix gcc-10 false positive on ubuntu-20.04
In function ‘memcpy’, inlined from ‘_ident_builder.constprop’
at msrp_signaling.c:1198:3:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:34:10: error:
‘__builtin___memcpy_chk’ writing 32 bytes into a region of size 18
overflows the destination [-Werror=stringop-overflow=]

   34 |   return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

(cherry picked from commit da3782ee3d113892c70183b8ae7731872dfb289a)