uac_registrant: Fix buggy gcc 7.x "uninitialized" error
reg_records.c:302:7: error: ‘new_elem’
    may be used uninitialized in this function

(cherry picked from commit 20fc08a49e1a8780b4cecb7251cc8243f368c0a5)