proto_ipsec: Correct fix for struct ordering issue in 45272908
Original error, on (clang-arm32-qemu-cross, ubuntu-22.04):

ipsec.c:384:19: error: field 'algo' with variable sized type
'struct xfrm_algo' not at the end of a struct or class is a GNU
extension [-Werror,-Wgnu-variable-sized-type-not-at-end]
  384 |         struct xfrm_algo algo;
      |                          ^

Credits to Răzvan Crainea for spotting the bug!

(cherry picked from commit a5890980ebd848eded8df9a3b9fd18d8b938f62e)