Don't pass unsigned short * into a function that expects unsigned int *. This fixes the following error building with gcc on ubuntu-22:
sipmemcache.c: In function `l_sipmemcache_server_add`:
../../ut.h:685:13: error: array subscript `unsigned int[0]` is partly outside array bounds of `in_port_t[1]` {aka `short unsigned int[1]`} [-Werror=array-bounds]
  685 |         *_r = 0;
      |         ~~~~^~~
sipmemcache.c:72:13: note: while referencing `iport`
   72 |   in_port_t iport = 0;
      |             ^~~~~