Fix pointer type on 32-bin ix86 machines
```
aaa_diameter.c: In function ‘dm_send_answer’:
aaa_diameter.c:420:60: error: passing argument 4 of ‘reverse_hex2int64’ from incompatible pointer type [-Wincompatible-pointer-types]
  420 |                 reverse_hex2int64(res.rs.s, res.rs.len, 1, &fd_req);
      |                                                            ^~~~~~~
      |                                                            |
      |                                                            long unsigned int *
In file included from aaa_diameter.c:26:
../../ut.h:399:78: note: expected ‘uint64_t *’ {aka ‘long long unsigned int *’} but argument is of type ‘long unsigned int *’
  399 | inline static int reverse_hex2int64( char *c, int len, int unsafe, uint64_t *r)
      |                                                                    ~~~~~~~~~~^
make[1]: *** [../../Makefile.rules:28: aaa_diameter.o] Error 1
make[1]: *** Waiting for unfinished jobs....
```

Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>
(cherry picked from commit 12bc40870e776f57e9f1449227408999d8d4f0fa)